---
abstract: 'TPath::Forester that understands Perl structs'
author:
  - 'David F. Houghton <dfhoughton@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  List::MoreUtils: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TPath-Forester-Ref
no_index: {}
requires:
  Moose: 0
  Moose::Exporter: 0
  Moose::Role: 0
  Moose::Util: 0
  MooseX::MethodAttributes: 0
  Scalar::Util: 0
  TPath::Expression: 0
  TPath::Forester: 0
  namespace::autoclean: 0
  perl: v5.10.0
version: 0.001
